datapaths:
  user_item_ratings: datasets/MIND/data/ratings.csv
  user_features:
  item_features:

split_per: 0.2
top_k: 10
temporal: True

models:

#takes 20 minutes for a combination
#  SVD:
#    parameters:
#      singular_values_n: [50]

  Popular:
    parameters:

  iALS:
    parameters:
      reg: [0.05]
      factors: [50]
      iter: [2,5]
      log: [True]
      random_state: [42]

  BPR:
    parameters:
      factors: [50]
      learning_rate: [0.01]
      reg: [0.01]
      iter: [20]
      random_state: [42]

  ItemKNN:
    parameters:
      neighbors: [20]
      similarity: [cosine, tfidf]

  EASE:
    parameters:
      lamb: [500]